public class Calculate {
public integer a,b,c;
     public static void add()
    {
        integer a,b,c;
        a=10;
        b=20;
        c=a+b;       
        system.debug('Addition of a and b='+c);
    }
     public void Sub()
    {  
        a=10;
        b=20;
        c=a-b;
        system.debug('Subtraction of a and b='+c);
    }
     public void Mult()
    {          
        a=9;
        b=9;
        c=a*b;
        system.debug('multiplication of a and b='+c);
    }        
    public void Div()
    {         
        a=40;
        b=8;
        c=a/b;        
        system.debug('Division of a and b='+c);
    }     
}