public class f1 {
   public integer a=10;        
   public integer b=30;
    public integer c=a+b;
        public f1(){
        system.debug('Execution++++++'+a);
        	}
    public void plot() {
    system.debug('In Plot Method++++++'+b);
    }
     public string plotString() {
         String Name='Sandeep';
       system.debug('In plotString Method++++++'+Name);
         return Name;
    }         
}