public class Maths {
    public decimal sum(decimal a,decimal b){
      return a+b;  
    }
    public decimal mult(decimal a,decimal b){
      return a*b;  
}
    public decimal sub(decimal a,decimal b){        
      return a-b;  
}
public string fullname(string firstname,string lastname){        
      return firstname+lastname ;  
}
    public static Integer getInt() { 
        integer MY_INT;
   return MY_INT; 
}
}